export default function CICDGitHubActionsContent() {
  return (
    <div className="prose prose-lg max-w-none">
      <h1 className="text-4xl font-bold text-gray-900 mb-8">9.2 CI/CD with GitHub Actions</h1>
      
      <div className="bg-green-50 border-l-4 border-green-500 p-6 mb-8">
        <h3 className="text-green-800 font-semibold mb-3">Modern CI/CD Implementation</h3>
        <ul className="text-green-700 space-y-2">
          <li>• Master GitHub Actions workflow automation</li>
          <li>• Build comprehensive testing pipelines</li>
          <li>• Implement continuous integration best practices</li>
          <li>• Automate deployment processes</li>
          <li>• Integrate security scanning and quality gates</li>
        </ul>
      </div>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">GitHub Actions Fundamentals</h2>
        
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-6">
          <h4 className="font-semibold text-blue-800 mb-3">GitHub Actions Core Concepts</h4>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h5 className="font-semibold text-blue-700 mb-3">Key Components:</h5>
              <ul className="text-blue-600 space-y-2 text-sm">
                <li>• <strong>Workflows:</strong> Automated processes defined in YAML</li>
                <li>• <strong>Events:</strong> Triggers that start workflows</li>
                <li>• <strong>Jobs:</strong> Sets of steps that execute on runners</li>
                <li>• <strong>Steps:</strong> Individual tasks within a job</li>
                <li>• <strong>Actions:</strong> Reusable units of code</li>
                <li>• <strong>Runners:</strong> Servers that execute workflows</li>
                <li>• <strong>Artifacts:</strong> Files generated by workflows</li>
              </ul>
            </div>
            
            <div>
              <h5 className="font-semibold text-blue-700 mb-3">Common Events:</h5>
              <ul className="text-blue-600 space-y-2 text-sm">
                <li>• <code>push</code> - Code pushed to repository</li>
                <li>• <code>pull_request</code> - PR opened/updated</li>
                <li>• <code>schedule</code> - Time-based triggers</li>
                <li>• <code>workflow_dispatch</code> - Manual triggers</li>
                <li>• <code>release</code> - Release created</li>
                <li>• <code>issues</code> - Issue events</li>
                <li>• <code>repository_dispatch</code> - External triggers</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="bg-gray-900 text-white p-6 rounded-lg mb-6">
          <h4 className="text-lg font-semibold mb-4">Basic GitHub Actions Workflow</h4>
          <div className="space-y-4">
            <div>
              <h5 className="font-semibold text-green-400 mb-3">Simple CI Workflow Structure</h5>
              <pre className="text-sm overflow-x-auto">
                <code>{`# .github/workflows/ci.yml
name: Continuous Integration

# Trigger events
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

# Environment variables
env:
  NODE_VERSION: '18'
  CACHE_KEY: \${{ runner.os }}-node-\${{ hashFiles('**/package-lock.json') }}

# Jobs run in parallel by default
jobs:
  # Linting and code quality
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run Prettier check
        run: npm run format:check
        
      - name: TypeScript type check
        run: npm run type-check
        
      - name: Check for unused dependencies
        run: npx depcheck
        
  # Unit and integration tests
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    # Test matrix for multiple Node versions
    strategy:
      matrix:
        node-version: [16, 18, 20]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm test -- --coverage --watchAll=false
        env:
          CI: true
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: \${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          
      - name: Run integration tests
        run: npm run test:integration
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/testdb
          
  # Build verification
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test] # Wait for other jobs
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            build/
            dist/
          retention-days: 30`}</code>
              </pre>
            </div>
          </div>
        </div>
      </section>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">Advanced Testing Pipelines</h2>
        
        <div className="grid md:grid-cols-3 gap-6 mb-6">
          <div className="bg-green-50 border border-green-200 rounded-lg p-6">
            <h3 className="text-xl font-semibold text-green-800 mb-4">🧪 Unit Testing</h3>
            <ul className="text-green-700 space-y-2 text-sm">
              <li>• Jest/Vitest configuration</li>
              <li>• Component testing (React Testing Library)</li>
              <li>• API testing (Supertest)</li>
              <li>• Mocking and fixtures</li>
              <li>• Coverage reporting</li>
            </ul>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
            <h3 className="text-xl font-semibold text-blue-800 mb-4">🔗 Integration Testing</h3>
            <ul className="text-blue-700 space-y-2 text-sm">
              <li>• Database integration</li>
              <li>• API endpoint testing</li>
              <li>• Service communication</li>
              <li>• Docker containers</li>
              <li>• Test data management</li>
            </ul>
          </div>

          <div className="bg-purple-50 border border-purple-200 rounded-lg p-6">
            <h3 className="text-xl font-semibold text-purple-800 mb-4">🌐 E2E Testing</h3>
            <ul className="text-purple-700 space-y-2 text-sm">
              <li>• Playwright/Cypress setup</li>
              <li>• User journey testing</li>
              <li>• Cross-browser testing</li>
              <li>• Visual regression testing</li>
              <li>• Performance testing</li>
            </ul>
          </div>
        </div>

        <div className="bg-gray-900 text-white p-6 rounded-lg">
          <h4 className="text-lg font-semibold mb-4">Comprehensive Testing Pipeline</h4>
          <div className="space-y-4">
            <div>
              <h5 className="font-semibold text-green-400 mb-3">Full-Stack Testing Workflow</h5>
              <pre className="text-sm overflow-x-auto">
                <code>{`# .github/workflows/test-pipeline.yml
name: Comprehensive Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  POSTGRES_VERSION: '15'
  REDIS_VERSION: '7'

jobs:
  # Unit tests with coverage
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: |
          npm run test:unit -- \\
            --coverage \\
            --coverageReporters=text-lcov \\
            --coverageReporters=json-summary \\
            --watchAll=false
        env:
          CI: true
          
      - name: Check coverage threshold
        run: |
          COVERAGE=\$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          if (( \$(echo "\$COVERAGE < 80" | bc -l) )); then
            echo "Coverage \$COVERAGE% is below 80% threshold"
            exit 1
          fi
          echo "Coverage: \$COVERAGE%"
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: \${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true

  # Integration tests with services
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    # Service containers
    services:
      postgres:
        image: postgres:\${{ env.POSTGRES_VERSION }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
      redis:
        image: redis:\${{ env.REDIS_VERSION }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup test database
        run: |
          npm run db:migrate
          npm run db:seed:test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379
          
      - name: Run integration tests
        run: npm run test:integration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret
          
      - name: Run API tests
        run: |
          npm run start:test &
          sleep 10
          npm run test:api
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379
          PORT: 3001

  # End-to-end tests
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Build application
        run: npm run build
        
      - name: Start application
        run: |
          npm run start:prod &
          npx wait-on http://localhost:3000 --timeout 60000
        env:
          NODE_ENV: production
          
      - name: Run Playwright tests
        run: npx playwright test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000
          
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: test-results/
          retention-days: 30

  # Performance tests
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Start application
        run: |
          npm run start:prod &
          npx wait-on http://localhost:3000
          
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: \${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Run load tests
        run: |
          npm install -g artillery
          artillery run tests/load/basic-load-test.yml`}</code>
              </pre>
            </div>
            
            <div>
              <h5 className="font-semibold text-blue-400 mb-3">Security & Quality Scanning</h5>
              <pre className="text-sm overflow-x-auto">
                <code>{`# Security and quality scanning job
  security-scan:
    name: Security & Quality Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarCloud
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      # Dependency vulnerability scanning
      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate
          npm audit --json > audit-report.json
          
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit-report.json
          
      # Static code analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: \${{ secrets.SONAR_TOKEN }}
          
      # Security scanning with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        
      # Container security scanning (if using Docker)
      - name: Build Docker image
        run: docker build -t app:test .
        
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app:test'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          
      # License compliance check
      - name: License compliance check
        run: |
          npx license-checker --summary --onlyAllow 'MIT;Apache-2.0;BSD;ISC;WTFPL'
          
  # Bundle analysis
  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with bundle analysis
        run: npm run build:analyze
        
      - name: Upload bundle stats
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: |
            build/static/js/*.js.map
            bundle-analyzer-report.html
            
      - name: Comment bundle size
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read bundle size information
            const buildDir = 'build/static/js';
            const jsFiles = fs.readdirSync(buildDir)
              .filter(f => f.endsWith('.js') && !f.endsWith('.map'))
              .map(f => ({
                name: f,
                size: fs.statSync(path.join(buildDir, f)).size
              }));
              
            const totalSize = jsFiles.reduce((sum, f) => sum + f.size, 0);
            const formattedSize = (totalSize / 1024).toFixed(2);
            
            const comment = \`
            ## Bundle Size Analysis 📦
            
            **Total JS Bundle Size:** \${formattedSize} KB
            
            | File | Size (KB) |
            |------|-----------|
            \${jsFiles.map(f => \`| \${f.name} | \${(f.size / 1024).toFixed(2)} |\`).join('\\n')}
            
            \${totalSize > 500 * 1024 ? '⚠️ Bundle size exceeds 500KB recommendation' : '✅ Bundle size looks good'}
            \`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });`}</code>
              </pre>
            </div>
          </div>
        </div>
      </section>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">Deployment Automation</h2>
        
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 mb-6">
          <h4 className="font-semibold text-yellow-800 mb-3">Deployment Strategies</h4>
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <h5 className="font-semibold text-yellow-700 mb-3">Frontend Deployment:</h5>
              <ul className="text-yellow-600 space-y-2 text-sm">
                <li>• Netlify/Vercel automatic deployments</li>
                <li>• AWS S3 + CloudFront static hosting</li>
                <li>• Preview deployments for PRs</li>
                <li>• Environment-specific configurations</li>
                <li>• Cache invalidation strategies</li>
              </ul>
            </div>
            
            <div>
              <h5 className="font-semibold text-yellow-700 mb-3">Backend Deployment:</h5>
              <ul className="text-yellow-600 space-y-2 text-sm">
                <li>• Docker container builds</li>
                <li>• Railway/Render deployment</li>
                <li>• AWS ECS/Lambda deployment</li>
                <li>• Database migrations</li>
                <li>• Health checks and rollback</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="bg-gray-900 text-white p-6 rounded-lg">
          <h4 className="text-lg font-semibold mb-4">Production Deployment Pipeline</h4>
          <div className="space-y-4">
            <div>
              <h5 className="font-semibold text-green-400 mb-3">Multi-Environment Deployment</h5>
              <pre className="text-sm overflow-x-auto">
                <code>{`# .github/workflows/deploy.yml
name: Deploy Application

on:
  push:
    branches:
      - main      # Production deployment
      - develop   # Staging deployment
  release:
    types: [published]

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: \${{ github.repository }}

jobs:
  # Build and test before deployment
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build

  # Build Docker image
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    outputs:
      image-digest: \${{ steps.build.outputs.digest }}
      image-tag: \${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: \${{ env.REGISTRY }}
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=\${{ github.ref_name }}-
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: \${{ steps.meta.outputs.tags }}
          labels: \${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: \${{ env.REGISTRY }}/\${{ env.IMAGE_NAME }}:\${{ github.sha }}
          format: spdx-json
          output-file: sbom.spdx.json
          
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

  # Deploy to staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-image
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.yourdomain.com
    
    steps:
      - name: Deploy to Railway (Staging)
        run: |
          curl -X POST \\
            -H "Authorization: Bearer \${{ secrets.RAILWAY_TOKEN }}" \\
            -H "Content-Type: application/json" \\
            -d '{
              "variables": {
                "IMAGE_TAG": "\${{ needs.build-image.outputs.image-tag }}",
                "ENVIRONMENT": "staging"
              }
            }' \\
            "https://backboard.railway.app/graphql/v2"
            
      - name: Run database migrations
        run: |
          # Run migrations against staging database
          npx prisma migrate deploy
        env:
          DATABASE_URL: \${{ secrets.STAGING_DATABASE_URL }}
          
      - name: Run smoke tests
        run: |
          npx wait-on https://staging.yourdomain.com/health --timeout 300000
          npm run test:smoke -- --baseURL=https://staging.yourdomain.com
          
      - name: Notify deployment
        uses: 8398a7/action-slack@v3
        with:
          status: \${{ job.status }}
          text: 'Staging deployment completed: https://staging.yourdomain.com'
        env:
          SLACK_WEBHOOK_URL: \${{ secrets.SLACK_WEBHOOK }}

  # Deploy to production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-image
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://yourdomain.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name production-cluster
        
      - name: Deploy to Kubernetes
        run: |
          # Update deployment with new image
          kubectl set image deployment/app \\
            app=\${{ needs.build-image.outputs.image-tag }} \\
            --namespace=production
            
          # Wait for rollout
          kubectl rollout status deployment/app --namespace=production --timeout=600s
          
      - name: Run database migrations
        run: |
          kubectl create job migration-\$(date +%s) \\
            --from=cronjob/migrations \\
            --namespace=production
        env:
          DATABASE_URL: \${{ secrets.PRODUCTION_DATABASE_URL }}
          
      - name: Health check
        run: |
          # Wait for deployment to be ready
          kubectl wait --for=condition=available deployment/app --timeout=300s --namespace=production
          
          # Verify health endpoint
          for i in {1..10}; do
            if curl -f https://yourdomain.com/health; then
              echo "Health check passed"
              break
            fi
            echo "Health check failed, retrying in 10s..."
            sleep 10
          done
          
      - name: Update monitoring
        run: |
          # Update deployment annotations for monitoring
          kubectl annotate deployment/app \\
            deployment.kubernetes.io/revision-\$(kubectl get deployment app -o jsonpath='{.metadata.annotations.deployment\.kubernetes\.io/revision}') \\
            --namespace=production`}</code>
              </pre>
            </div>
            
            <div>
              <h5 className="font-semibold text-blue-400 mb-3">Rollback and Monitoring</h5>
              <pre className="text-sm overflow-x-auto">
                <code>{`# Rollback workflow
  rollback:
    name: Emergency Rollback
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: production
    
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Rollback deployment
        run: |
          kubectl rollout undo deployment/app --namespace=production
          kubectl rollout status deployment/app --namespace=production
          
      - name: Notify rollback
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "🚨 Emergency rollback completed",
              attachments: [{
                color: "warning",
                fields: [{
                  title: "Environment",
                  value: "Production",
                  short: true
                }, {
                  title: "Triggered by",
                  value: "\${{ github.actor }}",
                  short: true
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: \${{ secrets.SLACK_WEBHOOK }}

  # Post-deployment monitoring
  post-deployment:
    name: Post-Deployment Monitoring
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: success() && github.ref == 'refs/heads/main'
    
    steps:
      - name: Wait for deployment stabilization
        run: sleep 300 # 5 minutes
        
      - name: Run production health checks
        run: |
          # Extended health checks
          curl -f https://yourdomain.com/health/detailed
          curl -f https://yourdomain.com/api/health
          
      - name: Performance check
        run: |
          # Basic performance validation
          RESPONSE_TIME=\$(curl -o /dev/null -s -w '%{time_total}' https://yourdomain.com)
          if (( \$(echo "\$RESPONSE_TIME > 2.0" | bc -l) )); then
            echo "Response time \$RESPONSE_TIME seconds is too slow"
            exit 1
          fi
          
      - name: Create deployment record
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              description: 'Automated production deployment',
              auto_merge: false
            });
            
      - name: Update status page
        run: |
          # Update external status page
          curl -X POST \\
            -H "Authorization: Bearer \${{ secrets.STATUS_PAGE_TOKEN }}" \\
            -d "status=operational&message=Deployment successful" \\
            "https://api.statuspage.io/v1/pages/\${{ secrets.PAGE_ID }}/incidents"

  # Security scan of deployed application
  security-scan-deployed:
    name: Security Scan (Deployed)
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: success() && github.ref == 'refs/heads/main'
    
    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://yourdomain.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: Upload ZAP results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: report_html.html`}</code>
              </pre>
            </div>
          </div>
        </div>
      </section>

      <div className="bg-gradient-to-r from-green-50 to-blue-50 border border-green-200 rounded-lg p-6">
        <h3 className="text-green-800 font-semibold mb-2">🚀 CI/CD Best Practices Checklist</h3>
        <p className="text-green-700 mb-3">
          Essential practices for building robust CI/CD pipelines that ensure code quality and reliable deployments.
        </p>
        <div className="grid md:grid-cols-4 gap-4 text-sm">
          <div>
            <strong className="text-green-700">Code Quality:</strong>
            <ul className="text-green-600 mt-1 space-y-1">
              <li>• Automated linting</li>
              <li>• Type checking</li>
              <li>• Code formatting</li>
              <li>• Security scanning</li>
            </ul>
          </div>
          <div>
            <strong className="text-green-700">Testing:</strong>
            <ul className="text-green-600 mt-1 space-y-1">
              <li>• Unit test coverage</li>
              <li>• Integration tests</li>
              <li>• E2E testing</li>
              <li>• Performance testing</li>
            </ul>
          </div>
          <div>
            <strong className="text-green-700">Deployment:</strong>
            <ul className="text-green-600 mt-1 space-y-1">
              <li>• Environment parity</li>
              <li>• Database migrations</li>
              <li>• Health checks</li>
              <li>• Rollback strategy</li>
            </ul>
          </div>
          <div>
            <strong className="text-green-700">Monitoring:</strong>
            <ul className="text-green-600 mt-1 space-y-1">
              <li>• Deployment tracking</li>
              <li>• Error monitoring</li>
              <li>• Performance metrics</li>
              <li>• Alert notifications</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}