export default function SolanaDevelopmentContent() {
  return (
    <div className="prose prose-lg max-w-none">
      <h1 className="text-4xl font-bold text-gray-900 mb-8">
        Solana Development
      </h1>

      <div className="bg-blue-50 border-l-4 border-blue-500 p-6 mb-8">
        <h3 className="text-blue-800 font-semibold mb-3">Key Concepts</h3>
        <ul className="text-blue-700 space-y-2">
          <li>• Program accounts</li>
          <li>• PDA (Program Derived Addresses)</li>
          <li>• CPI calls (Cross-Program Invocation)</li>
          <li>• SPL tokens</li>
        </ul>
      </div>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">Program Accounts</h2>
        <p>
          Solana programs (smart contracts) interact with accounts that store data and state. Each account is uniquely identified and can be owned by programs or users.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">Program Derived Addresses (PDA)</h2>
        <p>
          PDAs are deterministic addresses generated by programs for secure, permissionless account creation and management, without private keys.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">CPI Calls (Cross-Program Invocation)</h2>
        <p>
          CPI allows Solana programs to call other programs, enabling composability and complex interactions between smart contracts.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">SPL Tokens</h2>
        <p>
          SPL is Solana&apos;s token standard for fungible and non-fungible tokens. Programs can mint, transfer, and manage SPL tokens for DeFi, NFTs, and more.
        </p>
      </section>

      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6">
        <h3 className="text-blue-800 font-semibold mb-2">🌟 Tips for Success</h3>
        <ul className="text-blue-700 space-y-1 text-sm">
          <li>• Explore Solana&apos;s Rust SDK and Anchor framework</li>
          <li>• Practice creating and interacting with PDAs</li>
          <li>• Test CPI calls for composable dApps</li>
          <li>• Use SPL tokens for DeFi and NFT projects</li>
        </ul>
      </div>
    </div>
  );
}